export const START_LOADING = "START_LOADING";
export const FINISH_LOADING = "FINISH_LOADING";
export const LOAD_SEARCH_DATA = "LOAD_SEARCH_DATA";
export const CLEAR_SEARCH_DATA = "CLEAR_SEARCH_DATA";
export const ERROR_SEARCH_DATA = "ERROR_SEARCH_DATA";
